config/routes.rb
Hussy::Application.routes.draw do

  root :to => "pages#show", :controller => :page, :action => :show, :name => "welcome"
  
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  devise_scope :user do
 	 get "sign_up" => "users/registrations#new"
 	 post "users/registrations/create" => "users/registrations#create"
 	 post "users/registrations/edit" => "users/registrations#edit"
 	
  end
  
  match 'admin', :controller => 'pages', :action => 'admin_section'
  match 'search_form', :controller => 'patients', :action => 'search_form'
  match 'search', :controller => 'patients', :action=> 'search'
   
  

  resources :ethnicities

  resources :patients

  resources :consultations

  resources :classifications

  resources :characteristics

  resources :hospitals

  resources :medics

  resources :outcomes

  resources :drugs
  
  resources :roles
  
  resources :pages
  
  resources :properties
  
  resources :assays
  
  resources :treatments
  
  resources :referrals

  resources :results

  resources :therapies

end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
	belongs_to :consultation
	belongs_to :therapy
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  # GET /treatments
  # GET /treatments.xml
  def index
    @treatments = Treatment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @treatments }
    end
  end

  # GET /treatments/1
  # GET /treatments/1.xml
  def show
    @treatment = Treatment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @treatment }
    end
  end

  # GET /treatments/new
  # GET /treatments/new.xml
  def new
    @treatment = Treatment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @treatment }
    end
  end

  # GET /treatments/1/edit
  def edit
    @treatment = Treatment.find(params[:id])
  end

  # POST /treatments
  # POST /treatments.xml
  def create
    @treatment = Treatment.new(params[:treatment])

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to(@treatment, :notice => 'Treatment was successfully created.') }
        format.xml  { render :xml => @treatment, :status => :created, :location => @treatment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @treatment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /treatments/1
  # PUT /treatments/1.xml
  def update
    @treatment = Treatment.find(params[:id])

    respond_to do |format|
      if @treatment.update_attributes(params[:treatment])
        format.html { redirect_to(@treatment, :notice => 'Treatment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @treatment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.xml
  def destroy
    @treatment = Treatment.find(params[:id])
    @treatment.destroy

    respond_to do |format|
      format.html { redirect_to(treatments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.haml
= form_for(@treatment) do |f|
  - if @treatment.errors.any?
    #error_explanation
      %h2
        = pluralize(@treatment.errors.count, "error")
        prohibited this treatment from being saved:
      %ul
        - @treatment.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/treatments/_line_treatment.html.haml
= fields_for "consultation[treatments_attributes][]", treatment do |treatment_form|
  %tr
    %td.table_side_title
      = treatment.therapy.name
      = treatment_form.hidden_field :therapy_id, #{treatment.therapy.id}
    %td
      = treatment_form.select :treated, @options, :prompt => "Select one"
    %td
      = treatment_form.date_select :date_start, :index => treatment.id || "", :order => [:day, :month, :year], :include_blank => :true   
    %td
      = treatment_form.date_select :date_end, :index => treatment.id || "", :order => [:day, :month, :year], :include_blank => :true

app/views/treatments/edit.html.erb
<h1>Editing treatment</h1>

<%= render 'form' %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<h1>Listing treatments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @treatments.each do |treatment| %>
  <tr>
    <td><%= link_to 'Show', treatment %></td>
    <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
    <td><%= link_to 'Destroy', treatment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Treatment', new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New treatment</h1>

<%= render 'form' %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_treatment_path(@treatment) %> |
<%= link_to 'Back', treatments_path %>