config/routes.rb
Hussy::Application.routes.draw do

  root :to => "pages#show", :controller => :page, :action => :show, :name => "welcome"
  
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  devise_scope :user do
 	 get "sign_up" => "users/registrations#new"
 	 post "users/registrations/create" => "users/registrations#create"
 	 post "users/registrations/edit" => "users/registrations#edit"
 	
  end
  
  match 'admin', :controller => 'pages', :action => 'admin_section'
  match 'search_form', :controller => 'patients', :action => 'search_form'
  match 'search', :controller => 'patients', :action=> 'search'
   
  

  resources :ethnicities

  resources :patients

  resources :consultations

  resources :classifications

  resources :characteristics

  resources :hospitals

  resources :medics

  resources :outcomes

  resources :drugs
  
  resources :roles
  
  resources :pages
  
  resources :properties
  
  resources :assays
  
  resources :treatments
  
  resources :referrals

  resources :results

  resources :therapies

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
	
	has_many :physicals
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  # GET /characteristics
  # GET /characteristics.xml
  def index
    @characteristics = Characteristic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @characteristics }
    end
  end

  # GET /characteristics/1
  # GET /characteristics/1.xml
  def show
    @characteristic = Characteristic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @characteristic }
    end
  end

  # GET /characteristics/new
  # GET /characteristics/new.xml
  def new
    @characteristic = Characteristic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @characteristic }
    end
  end

  # GET /characteristics/1/edit
  def edit
    @characteristic = Characteristic.find(params[:id])
  end

  # POST /characteristics
  # POST /characteristics.xml
  def create
    @characteristic = Characteristic.new(params[:characteristic])

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to(@characteristic, :notice => 'Characteristic was successfully created.') }
        format.xml  { render :xml => @characteristic, :status => :created, :location => @characteristic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @characteristic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /characteristics/1
  # PUT /characteristics/1.xml
  def update
    @characteristic = Characteristic.find(params[:id])

    respond_to do |format|
      if @characteristic.update_attributes(params[:characteristic])
        format.html { redirect_to(@characteristic, :notice => 'Characteristic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @characteristic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.xml
  def destroy
    @characteristic = Characteristic.find(params[:id])
    @characteristic.destroy

    respond_to do |format|
      format.html { redirect_to(characteristics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_form.html.haml
= form_for(@characteristic) do |f|
  - if @characteristic.errors.any?
    #error_explanation
      %h2
        = pluralize(@characteristic.errors.count, "error")
        prohibited this characteristic from being saved:
      %ul
        - @characteristic.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :category
    %br/
    = f.text_field :category
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :unit
    %br/
    = f.text_field :unit
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/characteristics/edit.html.haml
%h1 Editing characteristic
= render 'form'
= link_to 'Show', @characteristic
|
\#{link_to 'Back', characteristics_path}

app/views/characteristics/index.html.haml
%h1 Listing characteristics
%table
  %tr
    %th Id
    %th Category
    %th Name
    %th Unit
    %th Description
    %td
    %td
    %td
  - @characteristics.each do |characteristic|
    %tr
      %td= characteristic.id
      %td= characteristic.category
      %td= characteristic.name
      %td= characteristic.unit
      %td= characteristic.description
      %td= link_to 'Show', characteristic
      %td= link_to 'Edit', edit_characteristic_path(characteristic)
      %td= link_to 'Destroy', characteristic, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Characteristic', new_characteristic_path

app/views/characteristics/new.html.haml
%h1 New characteristic
= render 'form'
= link_to 'Back', characteristics_path

app/views/characteristics/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_characteristic_path(@characteristic)
|
\#{link_to 'Back', characteristics_path}