config/routes.rb
Hussy::Application.routes.draw do

  root :to => "pages#show", :controller => :page, :action => :show, :name => "welcome"
  
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  devise_scope :user do
 	 get "sign_up" => "users/registrations#new"
 	 post "users/registrations/create" => "users/registrations#create"
 	 post "users/registrations/edit" => "users/registrations#edit"
 	
  end
  
  match 'admin', :controller => 'pages', :action => 'admin_section'
  match 'search_form', :controller => 'patients', :action => 'search_form'
  match 'search', :controller => 'patients', :action=> 'search'
   
  

  resources :ethnicities

  resources :patients

  resources :consultations

  resources :classifications

  resources :characteristics

  resources :hospitals

  resources :medics

  resources :outcomes

  resources :drugs
  
  resources :roles
  
  resources :pages
  
  resources :properties
  
  resources :assays
  
  resources :treatments
  
  resources :referrals

  resources :results

  resources :therapies

end

app/views/shards/_header.html.haml
#header
  .main_image= image_tag("hpa-logo.gif")
  .main_heading
    %h1.main HUSSy

app/views/shards/_login_bar.html.haml
.top_nav_container
  %ul#top_navigation
    - if user_signed_in?
      <li #{h @home_klass.to_s} >#{link_to "Home", root_path}
      - if current_user.role?('ADMIN')
        <li #{h @admin_klass} >#{link_to "Admin", admin_path}
      <li #{h @signout_klass} >#{link_to "Sign out", destroy_user_session_path, :method => :delete}
    - else
      <li #{h @home_klass} >#{link_to "Home", root_path}
      <li #{h @signout_klass} >#{link_to "Sign in", new_user_session_path}

app/views/shards/_menu.html.haml
= content_tag :div, :id => "left_sidebar" do
  - if user_signed_in?
    %p.local-title Navigation
    %ul.local
      %li
        = link_to "New Patient", search_form_path
      %li
        = link_to "Patient List", patients_path
      %li
        = link_to "Consultation List", consultations_path
  - else
    %p.local-title Navigation
    %ul.local
      %li
        = link_to "Sign in", new_user_session_path