config/routes.rb
Hussy::Application.routes.draw do

  root :to => "pages#show", :controller => :page, :action => :show, :name => "welcome"
  
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  devise_scope :user do
 	 get "sign_up" => "users/registrations#new"
 	 post "users/registrations/create" => "users/registrations#create"
 	 post "users/registrations/edit" => "users/registrations#edit"
 	
  end
  
  match 'admin', :controller => 'pages', :action => 'admin_section'
  match 'search_form', :controller => 'patients', :action => 'search_form'
  match 'search', :controller => 'patients', :action=> 'search'
   
  

  resources :ethnicities

  resources :patients

  resources :consultations

  resources :classifications

  resources :characteristics

  resources :hospitals

  resources :medics

  resources :outcomes

  resources :drugs
  
  resources :roles
  
  resources :pages
  
  resources :properties
  
  resources :assays
  
  resources :treatments
  
  resources :referrals

  resources :results

  resources :therapies

end

app/models/result.rb
class Result < ActiveRecord::Base
	has_many :outcomes
	has_many :consultations, :through => :outcomes
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.xml
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @results }
    end
  end

  # GET /results/1
  # GET /results/1.xml
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @result }
    end
  end

  # GET /results/new
  # GET /results/new.xml
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.xml
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to(@result, :notice => 'Result was successfully created.') }
        format.xml  { render :xml => @result, :status => :created, :location => @result }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.xml
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to(@result, :notice => 'Result was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.xml
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to(results_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.haml
= form_for(@result) do |f|
  - if @result.errors.any?
    #error_explanation
      %h2
        = pluralize(@result.errors.count, "error")
        prohibited this result from being saved:
      %ul
        - @result.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :category
    %br/
    = f.text_field :category
  .actions
    = f.submit

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.name %></td>
    <td><%= result.category %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @result.name %>
</p>

<p>
  <b>Category:</b>
  <%= @result.category %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>